"""init db

Revision ID: 3e012134021e
Revises:
Create Date: 2026-09-01 23:40:07.578205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e012134021e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_logs_ip_address"), "user_logs", ["ip_address"], unique=False
    )
    # ### end Alembic commands ###

    # Create the safe_inet_cast function
    op.execute("""
        CREATE OR REPLACE FUNCTION safe_inet_cast(text) RETURNS inet AS $$
        BEGIN
            RETURN $1::inet;
        EXCEPTION WHEN OTHERS THEN
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql IMMUTABLE;
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_logs_ip_address"), table_name="user_logs")
    op.drop_table("user_logs")
    # ### end Alembic commands ###

    # Drop the safe_inet_cast function
    op.execute("DROP FUNCTION IF EXISTS safe_inet_cast(text);")
